// src/services/dummyData.js
export const initialUsers = [
  { userId: 1, username: 'john_doe', name: 'John Doe', email: 'john@example.com', active: true },
  { userId: 2, username: 'jane_doe', name: 'Jane Doe', email: 'jane@example.com', active: false },
  { userId: 3, username: 'sam_smith', name: 'Sam Smith', email: 'sam@example.com', active: true },
  { userId: 4, username: 'lucy_hale', name: 'Lucy Hale', email: 'lucy@example.com', active: true },
  { userId: 5, username: 'mark_twain', name: 'Mark Twain', email: 'mark@example.com', active: false },
  { userId: 6, username: 'emma_watson', name: 'Emma Watson', email: 'emma@example.com', active: true },
  { userId: 7, username: 'noah_clark', name: 'Noah Clark', email: 'noah@example.com', active: true },
  { userId: 8, username: 'ava_jones', name: 'Ava Jones', email: 'ava@example.com', active: false },
  { userId: 9, username: 'oliver_miller', name: 'Oliver Miller', email: 'oliver@example.com', active: true },
  { userId: 10, username: 'mia_davis', name: 'Mia Davis', email: 'mia@example.com', active: false },
  { userId: 11, username: 'liam_wilson', name: 'Liam Wilson', email: 'liam@example.com', active: true },
  { userId: 12, username: 'sophia_lee', name: 'Sophia Lee', email: 'sophia@example.com', active: false },
  { userId: 13, username: 'benjamin_brown', name: 'Benjamin Brown', email: 'benjamin@example.com', active: true },
  { userId: 14, username: 'amelia_white', name: 'Amelia White', email: 'amelia@example.com', active: true },
  { userId: 15, username: 'ethan_green', name: 'Ethan Green', email: 'ethan@example.com', active: false },
  { userId: 16, username: 'isabella_wright', name: 'Isabella Wright', email: 'isabella@example.com', active: true },
  { userId: 17, username: 'james_jackson', name: 'James Jackson', email: 'james@example.com', active: true },
  { userId: 18, username: 'charlotte_harris', name: 'Charlotte Harris', email: 'charlotte@example.com', active: false },
  { userId: 19, username: 'alexander_thompson', name: 'Alexander Thompson', email: 'alexander@example.com', active: true },
  { userId: 20, username: 'mia_anderson', name: 'Mia Anderson', email: 'miaa@example.com', active: true },
  { userId: 21, username: 'michael_scott', name: 'Michael Scott', email: 'michael@example.com', active: false },
  { userId: 22, username: 'ava_taylor', name: 'Ava Taylor', email: 'ava_t@example.com', active: true },
  { userId: 23, username: 'william_moore', name: 'William Moore', email: 'william@example.com', active: true },
  { userId: 24, username: 'emily_clark', name: 'Emily Clark', email: 'emily@example.com', active: false },
  { userId: 25, username: 'daniel_martin', name: 'Daniel Martin', email: 'daniel@example.com', active: true },
  { userId: 26, username: 'ella_lewis', name: 'Ella Lewis', email: 'ella@example.com', active: false },
  { userId: 27, username: 'logan_king', name: 'Logan King', email: 'logan@example.com', active: true },
  { userId: 28, username: 'harper_allen', name: 'Harper Allen', email: 'harper@example.com', active: true },
  { userId: 29, username: 'jackson_walker', name: 'Jackson Walker', email: 'jackson@example.com', active: false },
  { userId: 30, username: 'grace_hill', name: 'Grace Hill', email: 'grace@example.com', active: true },
  { userId: 31, username: 'sebastian_wright', name: 'Sebastian Wright', email: 'sebastian@example.com', active: true },
  { userId: 32, username: 'ella_edwards', name: 'Ella Edwards', email: 'ella_ed@example.com', active: false },
  { userId: 33, username: 'lucas_evans', name: 'Lucas Evans', email: 'lucas@example.com', active: true },
  { userId: 34, username: 'lily_cooper', name: 'Lily Cooper', email: 'lily@example.com', active: true },
  { userId: 35, username: 'henry_collins', name: 'Henry Collins', email: 'henry@example.com', active: false },
  { userId: 36, username: 'grace_martin', name: 'Grace Martin', email: 'grace_m@example.com', active: true },
  { userId: 37, username: 'aiden_roberts', name: 'Aiden Roberts', email: 'aiden@example.com', active: true },
  { userId: 38, username: 'nora_james', name: 'Nora James', email: 'nora@example.com', active: false },
  { userId: 39, username: 'logan_perez', name: 'Logan Perez', email: 'logan_p@example.com', active: true },
  { userId: 40, username: 'olivia_morris', name: 'Olivia Morris', email: 'olivia@example.com', active: true },
];


export const initialPosts = [
  { postId: 1, caption: 'Beautiful sunset!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 2, caption: 'Great vacation!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 3, caption: 'Delicious homemade pizza!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 4, caption: 'Exploring the city at night!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 5, caption: 'Relaxing by the lake!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 6, caption: 'Morning coffee with a view!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 7, caption: 'A walk in the park!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 8, caption: 'Street art in the city!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 9, caption: 'Picnic in the countryside!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 10, caption: 'Snowy mountain peaks!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 11, caption: 'Cozy reading nook!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 12, caption: 'Sunset over the city skyline!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 13, caption: 'A night under the stars!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 14, caption: 'Day at the beach!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 15, caption: 'Mountain biking adventure!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 16, caption: 'Baking cookies with grandma!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 17, caption: 'Autumn leaves in the park!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 18, caption: 'Camping by the lake!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 19, caption: 'Watching the sunrise!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 20, caption: 'Vibrant street market!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 21, caption: 'Exploring ancient ruins!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 22, caption: 'Chasing waterfalls!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 23, caption: 'Freshly brewed coffee!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 24, caption: 'City skyline at dawn!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 25, caption: 'Forest hike!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 26, caption: 'Artistic graffiti!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 27, caption: 'Boat ride on the lake!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 28, caption: 'Desert sunset!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 29, caption: 'Tropical beach!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 30, caption: 'Winter wonderland!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 31, caption: 'Sunny pier!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 32, caption: 'Rainy day at the park!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 33, caption: 'Exploring a vineyard!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 34, caption: 'Golden hour in the city!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 35, caption: 'Cottage in the woods!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 36, caption: 'Mountain lake reflection!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 37, caption: 'Sunrise over the hills!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 38, caption: 'Family barbecue!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
  { postId: 39, caption: 'City lights at night!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: true },
  { postId: 40, caption: 'Vintage car show!', mediaUrl: 'https://res.cloudinary.com/dvzei06gf/image/upload/v1701595725/cld-sample.jpg', recent: false },
];
